export default {
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-primary-container': '#c8daff',
        'secondary-container': '#5dfd8a',
        'on-primary-fixed': '#001b3d',
        'inverse-surface': '#2d3133',
        'surface-container-low': '#f2f4f6',
        'surface-variant': '#e0e3e5',
        'surface-tint': '#005db6',
        'on-tertiary-container': '#73ecf6',
        'primary-fixed-dim': '#a9c7ff',
        'on-tertiary-fixed': '#002022',
        'surface-container-lowest': '#ffffff',
        background: '#f7f9fb',
        'on-primary': '#ffffff',
        'on-secondary-container': '#007232',
        'tertiary-fixed': '#7df4ff',
        'inverse-primary': '#a9c7ff',
        'error-container': '#ffdad6',
        'inverse-on-surface': '#eff1f3',
        'surface-dim': '#d8dadc',
        'on-secondary': '#ffffff',
        'surface-bright': '#f7f9fb',
        'surface-container-high': '#e6e8ea',
        'on-background': '#191c1e',
        outline: '#727783',
        'surface-container': '#eceef0',
        tertiary: '#005055',
        'on-tertiary': '#ffffff',
        'on-surface': '#191c1e',
        'tertiary-container': '#006a71',
        'tertiary-fixed-dim': '#5dd8e2',
        'on-primary-fixed-variant': '#00468c',
        primary: '#00478d',
        'on-tertiary-fixed-variant': '#004f54',
        'outline-variant': '#c2c6d4',
        secondary: '#006d2f',
        'primary-container': '#005eb8',
        'surface-container-highest': '#e0e3e5',
        'on-error-container': '#93000a',
        'on-secondary-fixed-variant': '#005322',
        'primary-fixed': '#d6e3ff',
        'on-secondary-fixed': '#002109',
        surface: '#f7f9fb',
        'on-surface-variant': '#424752',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'secondary-fixed': '#66ff8e',
        'secondary-fixed-dim': '#3de273',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: { DEFAULT: '0.5rem', lg: '0.5rem', xl: '0.75rem', full: '9999px' },
      maxWidth: {
        '8xl': '96rem',
      },
    },
  },
}
